name: ariadne_microns_pipeline
channels:
- menpo
- conda-forge
dependencies:
- python=2.7
- numpy
- cython
- opencv
- python-dateutil
- enum34
- mahotas
- h5py
- pandas
- scipy
- scikit-learn
- sqlalchemy
- luigi
- pyzmq
- scikit-image
- tifffile=0.11.1
- theano
